### ISSUE TITLE
Lokaler Pfad auswählen

### ISSUE THREAD

**Issue by ghost** [BennySRU/AC_SRU_Sync#1]
Lokaler Pfad ist AC Installationsverzeichnis. Fahrer wollen meist diesen Ordner angeben. Vereinzelt könnten einige ein anderes Verzeichnis für eine Testsynchronisation wählen. 

Falls genau eine ac.exe gefunden wird, lokalen Pfad automatisch setzen.
Falls mehrere ac.exe existieren, Liste zum Auswählen anbieten.
In jedem Fall als Fallback manuelle Pfadauswahl erlauben.

**Comment by BennySRU** [comment]
Erledigt
